name: Build

on: [push]

env:
  REGISTRY_HOSTNAME: oda2
  IMAGE_NAME: ibmcloud-login

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: build
        env:
          IMAGE_TAG: ${{ steps.vars.outputs.tag }}
        run: |
          docker build -t "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":"$IMAGE_TAG" .