name: Build

on: [push]

env:
  REGISTRY_HOSTNAME: globalhealthmonitor
  IMAGE_NAME: ibmcloud-cli

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: build
        env:
          IMAGE_TAG: latest
        run: |
          docker build -t "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":"$IMAGE_TAG" .
